name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello, World!
        run: echo "Hello, World!"

      # Runs a set of commands using the runners shell
      - name: Print Goodbye!
        run: echo "Goodbye!"
